### ISSUE TITLE
Device.connect got stuck

### ISSUE THREAD

**Issue by Eshwara** [tail-f-systems/JNC#132]
### Discussed in https://github.com/tail-f-systems/JNC/discussions/131

<div type='discussions-op-text'>

<sup>Originally posted by **Eshwara** April  3, 2023</sup>
Hi team,
i am connecting to device as below.

line 1  : 1 device = new Device("VNF", deviceuser, deviceIP, port);
line 2 : device.setDefaultReadTimeout(10 * 60 * 1000); // 10 minutes
line 3 : device.connect(username);

application got hang when it reached line 3. please find the thread dump below. anything we can do to avoid hang issue( waiting issue). it waits indefinitely and not able to come out that.

"pool-14-thread-6" #2671601 prio=5 os_prio=0 tid=0x00007f9b6002e800 nid=0xc854 in Object.wait() [0x00007f99c5360000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at ch.ethz.ssh2.auth.AuthenticationManager.deQueue(AuthenticationManager.java:90)
	- locked <0x000000045f39d7c8> (a java.util.Vector)
	at ch.ethz.ssh2.auth.AuthenticationManager.getNextMessage(AuthenticationManager.java:113)
	at ch.ethz.ssh2.auth.AuthenticationManager.authenticatePassword(AuthenticationManager.java:311)
	at ch.ethz.ssh2.Connection.authenticateWithPassword(Connection.java:328)
	- locked <0x000000045f3a1490> (a ch.ethz.ssh2.Connection)
	at com.tailf.jnc.SSHConnection.authenticateWithPassword(SSHConnection.java:126)
	at com.tailf.jnc.Device.auth(Device.java:580)
	at com.tailf.jnc.Device.connect(Device.java:427)
	at com.tailf.jnc.Device.connect(Device.java:399)</div>

**Comment by Eshwara** [comment]
@martin-volf  Thanks for the response. i will try to use connectimeout, is there any improvement in the newer version?. can you please help me with the steps to upgrade to new version?
