### ISSUE TITLE
Error during generating .java classes for yang files using jnc

### ISSUE THREAD

**Issue by shrikantkhapare** [tail-f-systems/JNC#135]
Hello,

We are seeing below errors when trying to generate .java classes from yang files using jnc. The issue is seen for tailf-ncs.yang and few other files only.

pyang -f jnc --jnc-output src/gen tailf-ncs.yang
Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/pyang/plugins/jnc.py", line 800, in _search
iterate(stmt.i_children, acc)
AttributeError: i_children

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/pyang/plugins/jnc.py", line 552, in pairwise
item = next(iterator) # throws StopIteration if empty.
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/usr/local/bin/pyang", line 493, in
run()
File "/usr/local/bin/pyang", line 462, in run
emit_obj.emit(ctx, modules, fd)
File "/usr/local/lib/python3.8/dist-packages/pyang/plugins/jnc.py", line 208, in emit
self.generate_from(module)
File "/usr/local/lib/python3.8/dist-packages/pyang/plugins/jnc.py", line 247, in generate_from
generator.generate()
File "/usr/local/lib/python3.8/dist-packages/pyang/plugins/jnc.py", line 998, in generate
self.generate_classes()
File "/usr/local/lib/python3.8/dist-packages/pyang/plugins/jnc.py", line 1097, in generate_classes
child_generator.generate()
File "/usr/local/lib/python3.8/dist-packages/pyang/plugins/jnc.py", line 1000, in generate
self.generate_class()
File "/usr/local/lib/python3.8/dist-packages/pyang/plugins/jnc.py", line 1202, in generate_class
field = self.generate_child(ch)
File "/usr/local/lib/python3.8/dist-packages/pyang/plugins/jnc.py", line 1286, in generate_child
child_gen = MethodGenerator(sub, self.ctx)
File "/usr/local/lib/python3.8/dist-packages/pyang/plugins/jnc.py", line 1884, in init
search(stmt, yangelement_stmts | leaf_stmts)]
File "/usr/local/lib/python3.8/dist-packages/pyang/plugins/jnc.py", line 804, in search
search(stmt, keywords, dict)
File "/usr/local/lib/python3.8/dist-packages/pyang/plugins/jnc.py", line 802, in _search
iterate(stmt.substmts, acc)
File "/usr/local/lib/python3.8/dist-packages/pyang/plugins/jnc.py", line 779, in iterate
key = ' '.join([ch.keyword, camelize(ch.arg)])
File "/usr/local/lib/python3.8/dist-packages/pyang/plugins/jnc.py", line 589, in camelize
for character, next_character in iterator:
RuntimeError: generator raised StopIteration

Please help identify the exact error. The error is seen for only a handful of yang files like tailf-ncs.yang. For remaining yang files, the java classes are generated without any errors/warnings.

Thanks,
Shrikant

**Comment by shrikantkhapare** [comment]
Seems like the issue was with Python version(3.7). Followed the solution mentioned in [link](https://stackoverflow.com/questions/51700960/runtimeerror-generator-raised-stopiteration-every-time-i-try-to-run-app) and the issue was fixed.

**Comment by martin-volf** [comment]
Can you post the module or the relevant part of a module that is causing the error? The changes in Python 3.7 are somewhat relevant indeed, but I don't think the original problem is exactly caused by that.

**Comment by shrikantkhapare** [comment]
The error was seen in jnc.py rather than the yang modules. After shifting to Python 2.7.17 those errors were not seen

**Comment by martin-volf** [comment]
I understand that the YANG modules were syntactically correct; but we are using Python 3.7 or later and do not have this issue, so if you do, I assume it is caused by something special in your YANG modules and we would like to reproduce the problem in our environment.
