### ISSUE TITLE
Session closed

### ISSUE THREAD

**Issue by tomek-jaworski-elb** [tail-f-systems/JNC#141]
Hi,
I'm connecting to Cisco router successfully. After sending request to get configuration or just only simple get() during retrieving of data I receive IOEXception and session closed.

faulty method
_**NodeSet elements = session.getConfig();**_

log
_Caused by: java.io.IOException: Session closed
	at com.tailf.jnc.SSHSession$SessionDataReader.readData(SSHSession.java:138)
	at com.tailf.jnc.framing.NC1_1_Framer.readChunkHeader(Framer.java:144)
	at com.tailf.jnc.framing.NC1_1_Framer.parseFrame(Framer.java:164)
	at com.tailf.jnc.SSHSession.readOne(SSHSession.java:258)
	at com.tailf.jnc.NetconfSession.recvRpcReply(NetconfSession.java:1527)
	at com.tailf.jnc.NetconfSession.recvRpcReplyData(NetconfSession.java:1511)
	at com.tailf.jnc.NetconfSession.getConfig(NetconfSession.java:460)
	at com.tailf.jnc.NetconfSession.getConfig(NetconfSession.java:449)_

Do You have any idea how to solve this error?

**Comment by martin-volf** [comment]
`development` has already been merged to `master`, and `master` is actually a couple of commits ahead of that now and `development` should have been already deleted. So whatever works in `development`, *should* work in `master` too.

You may want to increase the debug level - it can be done by calling the static method `Element.setDebugLevel(int)` early on in your code, the level ranges from 0 for no debug info up to 4. (Yes, I know, we should have implemented standard logging mechanism long ago.)

**Comment by tomek-jaworski-elb** [comment]
Thank you for your quick reply and debugging tip.
However, the device operation on the master branch still does not work, I receive information
`end of input (-1)`
and then
`java.io.IOException: Session closed`

Is there any solution for this issue?

**Comment by martin-volf** [comment]
At this point we have no clue as to where the issue is, or even if there is
any, we need your help in reproducing it on our side. Are you able to get the
traffic between the client and the device? The debug output with level at least
2 contains the traffic, or possibly the device logs that somewhere too.

The `end of input` means that the device closed the stream, you should be able
to find a reason for that in device's logs too.

**Comment by tomek-jaworski-elb** [comment]
I have no idea how to printout a receiving stream.
But I've found a place where is the issue. Incoming stream is filled by 0 and in this case method from line 134 returns -1.
Attaching some code from debug mode.

![image](https://github.com/tail-f-systems/JNC/assets/95344740/3eb470ea-a28f-4cee-a635-923c5db89f2d)
