### ISSUE TITLE
Device.close

### ISSUE THREAD

**Issue by bndeshpande** [tail-f-systems/JNC#148]
Hi Team,

Below is code where create device followed by some netconf sessions opened.

String emsUserName = "bobby";
String IP = "10.10.10.10";
duser = new DeviceUser(emsUserName, "admin", "admin");
dev = new Device("mydev", duser, IP, 2022);
dev.connect(emsUserName, 0, false);
dev.newSession("cfg");

device.newSession(IP + "_" + RPC_SESSION);
device.newSession(IP + "_" + SW_RELEASE_SESSION);
device.newSession(IP + "_" + DOWNLOAD_SESSION);

so when try to close device using device.close() method like below

First I will be doing

device.setSOTimeOut(60000);
device.closeSession(IP + "_" + RPC_SESSION);
device.closeSession(IP + "_" + SW_RELEASE_SESSION);
device.closeSession(IP + "_" + DOWNLOAD_SESSION);
device.close(60000); 

So instead of closing opened netconf sessions followed by device.close(), just call device.close() will take care of closing all opened netconf session during device create?

Since Some time I am getting below exception while device.close() and call home will not be closed. 

at com.tailf.jnc.Device.close(Device.java:350)

Please help me on this.

Is device.close() will not terminate all previously opened ssh connection which is not closed hanging at confd side?

**Comment by martin-volf** [comment]
There is only one SSH connection per device instance. A session is not a SSH connection, it is just a new SSH channel over that connection. So if you call `Device.close()`, it closes the SSH connection and all channels are closed automatically, no need to close them manually.

**Comment by bndeshpande** [comment]
> There is only one SSH connection per device instance. A session is not a SSH connection, it is just a new SSH channel over that connection. So if you call `Device.close()`, it closes the SSH connection and all channels are closed automatically, no need to close them manually.

Thanks for reply. In one of our production setup, our application called device.close() on SSH connection as mentioned above, but still one session is still hanging at confd which is not closed which is found from audit and netconf.log related to that device.

<INFO> 16-Feb-2024::06:00:03.844 confd[638]: audit user: admin/783529 assigned to groups: admin
<INFO> 16-Feb-2024::06:00:03.844 confd[638]: audit user: admin/783529 created new session via netconf from <application-ip:port> with ssh

And device.close called on 19th-Feb-08:31 timestamp at that time application called close sessions which opened as mentioned above and same thing reflected in audit log as below:

<INFO> 19-Feb-2024::08:21:01.657 confd[638]: audit user: admin/785679 terminated session (reason: normal)
<INFO> 19-Feb-2024::08:31:19.401 confd[638]: audit user: admin/781478 terminated session (reason: dropped)
<INFO> 19-Feb-2024::08:31:19.402 confd[638]: audit user: admin/781479 terminated session (reason: dropped)
<INFO> 19-Feb-2024::08:31:19.403 confd[638]: audit user: admin/781481 terminated session (reason: dropped)
<INFO> 19-Feb-2024::08:31:19.404 confd[638]: audit user: admin/781482 terminated session (reason: dropped)
<INFO> 19-Feb-2024::08:31:19.405 confd[638]: audit user: admin/781483 terminated session (reason: dropped)
<INFO> 19-Feb-2024::08:31:19.405 confd[638]: audit user: admin/781484 terminated session (reason: dropped)
<INFO> 19-Feb-2024::08:31:19.406 confd[638]: audit user: admin/781485 terminated session (reason: dropped)
<INFO> 19-Feb-2024::08:31:19.407 confd[638]: audit user: admin/781486 terminated session (reason: dropped)

Here not seen terminating of opened session 783529, seems due to this device.close throws 
NullPointer Exception

at com.tailf.jnc.Device.close(Device.java:350).

If device.close() will take care of closing all opened sessions, is there any duration needs to wait for the same? Like whether this device.close() needs to keep it loop for certain period of time? If so how many seconds or mins needs to wait?

**Comment by martin-volf** [comment]
So the problem is not that `Device.close()` does not close all sessions, the problem is that it throws an NPE (and yes, in that case some sessions may remain open, in particular because the SSH session stays open, at least until the socket is GC'ed).

Can you show a bit more from the exception stackstrace?  Also, I'm a bit puzzled by the part you posted, `Device.java:350` - that line does not contain any executable code, and as far as I can tell, no version of the file had the method `close()` at that line; what version are you using, do you have your own modifications?

**Comment by bndeshpande** [comment]
So the problem is not that Device.close() does not close all sessions, the problem is that it throws an NPE (and yes, in that case some sessions may remain open, in particular because the SSH session stays open, at least until the socket is GC'ed).

If session remain opens how to close that session, is device.close() will not take care of clearing old hanging session? Is there any JNC api to get all sessions related to device? So how much time needs to wait for device.close will close all open sessions? 

Can you show a bit more from the exception stackstrace? Also, I'm a bit puzzled by the part you posted, Device.java:350 - that line does not contain any executable code, and as far as I can tell, no version of the file had the method close() at that line; what version are you using, do you have your own modifications?

Below is stack trace : 
at com.tailf.jnc.Device.close(Device.java:350)
	at com.mavenir.netconf.util.SmDeviceUtil.lambda$deleteSmDevice$11(SmDeviceUtil.java:715)
	at java.lang.Thread.run(Thread.java:750)

Below is JNC device close method 

/**
     * end all NETCONF sessions and close the SSH socket associated to this
     * device It also clears all accumulated config trees.
     */
    public void close(int timeOut) {
        for (int i = 0; i < connSessions.size(); i++) {
            final SessionConnData d = connSessions.get(i);
            try {
                d.session.closeSession();
            } catch (final Exception e) {
            }
        }
        connSessions = new ArrayList<SessionConnData>();
        for (int i = 0; i < trees.size(); i++) {
            final SessionTree t = trees.get(i);
            t.configTree = null;  // this is 350 line.
        }
        // we keep the named config trees
        if (con != null) {
            con.close(timeOut);
            con = null;
        }
    }

**Comment by martin-volf** [comment]
With the current API you can only call `Device.closeSession(String name)`, there is no direct access to the session list.  But again, I suggest you concentrate on the exception - if `Device.close()` finishes successfully, there would be no need to deal with individual sessions.

And here is the problem - we cannot help you much, you are using your own modifications.  The only thing I can see from the code you posted is that it fails due to that `trees.get(i)` returns `null` at some point; with the current code, I don't think it is ever possible that `null` appears in the list, so my conclusion is that your modifications somehow causes that.

**Comment by bndeshpande** [comment]
Hi @martin-volf ,

With the current API you can only call Device.closeSession(String name), there is no direct access to the session list. But again, I suggest you concentrate on the exception - if Device.close() finishes successfully, there would be no need to deal with individual sessions.

Okay if there is no API, can you please let me know for how long application needs to wait once it trigger Device.close() method. Current code is like below mentioned where device.close will be called within thread block. So do we need to add any timer for specific time period which allows to close all open ssh sessions?

if (device != null) {
				Thread t = new Thread(() -> {
					try {
						device.setSOTimeOut(DEFAULT_SOCKET_TIMEOUT);
						closeSmSubscriptions(smIP, device, true);
						log.error("Calling device close.");
						device.close(DEFAULT_SOCKET_TIMEOUT);
						log.error("Device is closed.");
						isDeleted[0] = true;
					} catch (Exception e) {
						log.error("Error while closing the device " + smIP);
						log.error(e.getMessage(),e);
						isDeleted[0] = false;
					}
				});
				t.start();

And I have downloaded new JNC with SSHJ support but there facing issue where application tries to connect incoming callhome and it got stuck in device.connect() method itself. Further subscription and other thing not happening. Please help on this as well. For this issue already opened new thread under this https://github.com/tail-f-systems/JNC/issues/139
