### ISSUE TITLE
JNC device connect failing during callhome for sha256 kex new algorithm.

### ISSUE THREAD

**Issue by bndeshpande** [tail-f-systems/JNC#149]
Hi Team,

                The call home server confd ssh kex algoritham has been changed to diffie-hellman-group-exchange-sha256 and mac to hmac-sha2-256 then JNC device not able to connect and throwing below exceptions while device.connect method. Please help to check the same.

        at ch.ethz.ssh2.Connection.connect(Connection.java:814)
        at com.tailf.jnc.SSHConnection.<init>(SSHConnection.java:28)
        at com.tailf.jnc.Device.connect(Device.java:424)

Caused by: java.io.IOException: Key exchange was not finished, connection is closed.
        at ch.ethz.ssh2.transport.KexManager.getOrWaitForConnectionInfo(KexManager.java:98)
        at ch.ethz.ssh2.transport.TransportManager.getConnectionInfo(TransportManager.java:251)
        at ch.ethz.ssh2.Connection.connect(Connection.java:770)
        ... 9 more
Caused by: java.io.IOException: Cannot negotiate, proposals do not match.
        at ch.ethz.ssh2.transport.KexManager.handleMessage(KexManager.java:426)
        at ch.ethz.ssh2.transport.TransportManager.receiveLoop(TransportManager.java:827)
        at ch.ethz.ssh2.transport.TransportManager$1.run(TransportManager.java:497)
        ... 1 more

**Comment by martin-volf** [comment]
This is from an old version of the library that still used the old Ganymed SSH client library. We do not support this, I'm sorry.

**Comment by bndeshpande** [comment]
> This is from an old version of the library that still used the old Ganymed SSH client library. We do not support this, I'm sorry.

Could you please tell us which library will support diffie-hellman-group-exchange-sha256 and hmac-sha2-256 algorithms which JNC communicate through?

**Comment by martin-volf** [comment]
I'm not sure what you mean by "library". SSHJ supports both of them, plus quite a few more, so JNC, which in its recent releases uses SSHJ, supports them too out of the box.
