### ISSUE TITLE
JNC fails to generate Java codes from Cisco IOS yang file

### ISSUE THREAD

**Issue by TatsuyaIwashita** [tail-f-systems/JNC#46]
Hi,
I met the error when I tried to generate Java codes from Cisco IOS yang file.

```
$ python -V
Python 2.7.5
$ $NCS_DIR/bin/pyang -v
pyang 1.5
$ sha1sum $NCS_DIR/lib/pyang/pyang/plugins/jnc.py
6b638501be25215b4edfe444f7931005ce83eeeb  /home/ncs/ncs/lib/pyang/pyang/plugins/jnc.py
$ sha1sum $NCS_DIR/packages/neds/cisco-ios/src/yang/tailf-ned-cisco-ios.yang 
a35881ee4b415e7deb338c7e78a4508e26ef76a3  /home/ncs/ncs/packages/neds/cisco-ios/src/yang/tailf-ned-cisco-ios.yang
$
$ cd ./test
$ $NCS_DIR/bin/pyang -f jnc -d . $NCS_DIR/packages/neds/cisco-ios/src/yang/tailf-ned-cisco-ios.yang --jnc-debug --jnc-verbose 2>&1 | tail -35
Writing file to: /home/ncs/jnc/test/src/gen/tailfNedCiscoIos/router/bgp/bgp/nexthop/Trigger.java
pkg gen.tailfNedCiscoIos.router.bgp.bgp.nexthop generated
Generating "Nexthop.java"...
Writing file to: /home/ncs/jnc/test/src/gen/tailfNedCiscoIos/router/bgp/bgp/Nexthop.java
Generating "Regexp.java"...
Writing file to: /home/ncs/jnc/test/src/gen/tailfNedCiscoIos/router/bgp/bgp/Regexp.java
pkg gen.tailfNedCiscoIos.router.bgp.bgp generated
Generating "Bgp.java"...
Writing file to: /home/ncs/jnc/test/src/gen/tailfNedCiscoIos/router/bgp/Bgp.java
Traceback (most recent call last):
  File "/home/ncs/ncs/lib/pyang/bin/pyang", line 411, in <module>
    run()
  File "/home/ncs/ncs/lib/pyang/bin/pyang", line 383, in run
    emit_obj.emit(ctx, modules, fd)
  File "/home/ncs/ncs/lib/pyang/pyang/plugins/jnc.py", line 213, in emit
    self.generate_from(module)
  File "/home/ncs/ncs/lib/pyang/pyang/plugins/jnc.py", line 250, in generate_from
    generator.generate()
  File "/home/ncs/ncs/lib/pyang/pyang/plugins/jnc.py", line 995, in generate
    self.generate_classes()
  File "/home/ncs/ncs/lib/pyang/pyang/plugins/jnc.py", line 1093, in generate_classes
    child_generator.generate()
  File "/home/ncs/ncs/lib/pyang/pyang/plugins/jnc.py", line 997, in generate
    self.generate_class()
  File "/home/ncs/ncs/lib/pyang/pyang/plugins/jnc.py", line 1190, in generate_class
    field = self.generate_child(ch)
  File "/home/ncs/ncs/lib/pyang/pyang/plugins/jnc.py", line 1274, in generate_child
    child_generator.generate()
  File "/home/ncs/ncs/lib/pyang/pyang/plugins/jnc.py", line 997, in generate
    self.generate_class()
  File "/home/ncs/ncs/lib/pyang/pyang/plugins/jnc.py", line 1190, in generate_class
    field = self.generate_child(ch)
  File "/home/ncs/ncs/lib/pyang/pyang/plugins/jnc.py", line 1293, in generate_child
    access_method.modifiers = [f(x) for x in access_method.modifiers]
AttributeError: 'list' object has no attribute 'modifiers'
```
How do i address the error?

Thanks.

**Comment by klacke** [comment]
Hi,

The java class generation code isn't really up to speed. I'd suggest
that you just skip that step, and use the nice text-based DOM to
manipulate the payload tress instead. That work perfect today, and
is very easy to understand.

/klacke

**Comment by TatsuyaIwashita** [comment]
I was disappointed at that but I'll try the text-based one.
Thanks.

**Comment by klacke** [comment]
Yes I understand, OTOH the idea of generating Java classes for device models actually sounded netter than it really was. Datamodels for real devices, such as Juniper, IOS XR etc, are so massive so the amount of genererated classes become - well too many.
I personally prefer the text dom, combine that with 'pyang -f tree' and you're good to go.
Good luck

/klacke
